[tool.poetry]
name = "sci"
version = "0.1.0"
description = ""
authors = ["cole-wilson <wilsoncb@students.osd.wednet.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
ratelimit = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
